server:
  port: 8082

spring:
  application:
    name: devworks-cart-order-service
#services:
#  product:
#    base-url=${PRODUCT_SERVICE_URL:http://localhost:8082}
#  inventory:
#    base-url=${INVENTORY_SERVICE_URL:http://localhost:8083}
